# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DISCUSSIT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DISCUSSIT(object):
    def setupUi(self, DISCUSSIT):
        DISCUSSIT.setObjectName("DISCUSSIT")
        DISCUSSIT.resize(910, 692)
        self.verticalLayoutWidget = QtWidgets.QWidget(DISCUSSIT)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 871, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chats = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.chats.setObjectName("chats")
        self.horizontalLayout_3.addWidget(self.chats)
        self.users_lists = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.users_lists.setMaximumSize(QtCore.QSize(200, 16777215))
        self.users_lists.setObjectName("users_lists")
        self.horizontalLayout_3.addWidget(self.users_lists)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.message.setObjectName("message")
        self.horizontalLayout.addWidget(self.message)
        self.send_message = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.send_message.setAutoDefault(True)
        self.send_message.setDefault(True)
        self.send_message.setObjectName("send_message")
        self.horizontalLayout.addWidget(self.send_message)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DISCUSSIT)
        QtCore.QMetaObject.connectSlotsByName(DISCUSSIT)

    def retranslateUi(self, DISCUSSIT):
        _translate = QtCore.QCoreApplication.translate
        DISCUSSIT.setWindowTitle(_translate("DISCUSSIT", "Form"))
        self.send_message.setText(_translate("DISCUSSIT", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DISCUSSIT = QtWidgets.QWidget()
    ui = Ui_DISCUSSIT()
    ui.setupUi(DISCUSSIT)
    DISCUSSIT.show()
    sys.exit(app.exec_())
